---
- name: Example playbook
  hosts: ubuntu
  user: ubuntu
  become: true
  become_method: sudo 
  tasks:




  - name: Install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
    with_items:
    - apache2
    - telnet
    - unzip
    
        
        
...