---
- name: Example playbook
  hosts: ubuntu
  user: ubuntu
  become: true
  become_method: sudo 
  tasks:




  - name: Install apache2
    package:
      name: apache2
      state: present      #latest      #absent
...