---
- name: Example playbook
  hosts: ubuntu
  user: ubuntu
  become: true
  become_method: sudo 
  tasks:




  - name: Install apache2
    ansible.builtin.package:
      name: 
        - apache2
        - telnet
        - unzip
      state: present      #latest      #absent
...